package handlers





























































































}	json.NewEncoder(w).Encode(results)	}		})			"created_at": a.CreatedAt,			"content":    a.Content,			"title":      a.Title,			"id":         a.ID,		results = append(results, map[string]interface{}{	for _, a := range announcements {	results := make([]map[string]interface{}, 0, len(announcements))	}		return		json.NewEncoder(w).Encode([]interface{}{})		log.Printf("strapi GetAllAnnouncements: %v", err)	if err != nil {	announcements, err := h.strapi.GetAllAnnouncements()	w.Header().Set("Content-Type", "application/json")func (h *Handler) AnnouncementsAPI(w http.ResponseWriter, r *http.Request) {// expected by the frontend JS (id, title, content, created_at).// AnnouncementsAPI proxies Strapi announcements as JSON in the legacy format}	h.templates.ExecuteTemplate(w, "contact.html", data)	data := map[string]interface{}{"Title": "Hubungi Kami"}func (h *Handler) Contact(w http.ResponseWriter, r *http.Request) {}	h.templates.ExecuteTemplate(w, "announcements.html", data)	data := map[string]interface{}{"Title": "Pengumuman"}func (h *Handler) Announcements(w http.ResponseWriter, r *http.Request) {}	h.templates.ExecuteTemplate(w, "about.html", data)	data := map[string]interface{}{"Title": "Tentang Kami"}func (h *Handler) About(w http.ResponseWriter, r *http.Request) {}	h.templates.ExecuteTemplate(w, "index.html", data)	}		data["Announcements"] = items		}			})				"CreatedAt": a.CreatedAt,				"Content":   a.Content,				"Title":     a.Title,				"ID":        a.ID,			items = append(items, map[string]interface{}{		for _, a := range announcements {		items := make([]map[string]interface{}, 0, len(announcements))	} else {		log.Printf("strapi GetAnnouncements: %v", err)	if err != nil {	announcements, err := h.strapi.GetAnnouncements(5)	}		"Title": "Beranda",	data := map[string]interface{}{	}		return		http.NotFound(w, r)	if r.URL.Path != "/" {func (h *Handler) Home(w http.ResponseWriter, r *http.Request) {}	}		templates: tmpl,		strapi:    sc,	return &Handler{	tmpl := template.Must(template.ParseGlob("templates/*.html"))func New(sc *strapi.Client) *Handler {// New returns a Handler backed by the given Strapi client.}	templates *template.Template	strapi    *strapi.Clienttype Handler struct {// Handler holds shared dependencies for all HTTP handlers.)	"webapp/internal/strapi"	"text/template"	"net/http"	"log"	"encoding/json"import (package handlers